version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local