- name: Deploy RoundCube container
  hosts: localhost
  tasks:
    - name: Deploy RoundCube container
      docker_container:
        name: roundcube
        image: crapstur/roundcubemail
        ports:
          - "8081:80"
        volumes:
          - /Users/rcapouillez/Documents/Development/Ynov/automatisation/jenkins-ynov/srv/roundcube:/var/www/html
        restart_policy: always